import { Product, Category, Brand, HealthConcern } from '../types';

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Medicines', slug: 'medicines', imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=80', createdAt: new Date().toISOString() },
  { id: 'cat-2', name: 'Wellness & Supplements', slug: 'wellness-supplements', imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=300&auto=format&fit=crop&q=80', createdAt: new Date().toISOString() },
  { id: 'cat-3', name: 'Personal Care', slug: 'personal-care', imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&auto=format&fit=crop&q=80', createdAt: new Date().toISOString() },
  { id: 'cat-4', name: 'Ayurveda & Herbs', slug: 'ayurveda-herbs', imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=300&auto=format&fit=crop&q=80', createdAt: new Date().toISOString() },
  { id: 'cat-5', name: 'Baby Care', slug: 'baby-care', imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=300&auto=format&fit=crop&q=80', createdAt: new Date().toISOString() },
  { id: 'cat-6', name: 'Health Devices', slug: 'health-devices', imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=300&auto=format&fit=crop&q=80', createdAt: new Date().toISOString() },
];

export const mockBrands: Brand[] = [
  { id: 'brand-1', name: 'Cipla', slug: 'cipla', logoUrl: 'https://placehold.co/120x60/faf5ff/6b21a8?text=Cipla', createdAt: new Date().toISOString() },
  { id: 'brand-2', name: 'Sun Pharma', slug: 'sun-pharma', logoUrl: 'https://placehold.co/120x60/faf5ff/6b21a8?text=Sun+Pharma', createdAt: new Date().toISOString() },
  { id: 'brand-3', name: 'Himalaya Wellness', slug: 'himalaya', logoUrl: 'https://placehold.co/120x60/faf5ff/6b21a8?text=Himalaya', createdAt: new Date().toISOString() },
  { id: 'brand-4', name: 'Dabur', slug: 'dabur', logoUrl: 'https://placehold.co/120x60/faf5ff/6b21a8?text=Dabur', createdAt: new Date().toISOString() },
  { id: 'brand-5', name: 'Dr. Morepen', slug: 'dr-morepen', logoUrl: 'https://placehold.co/120x60/faf5ff/6b21a8?text=Dr.+Morepen', createdAt: new Date().toISOString() },
  { id: 'brand-6', name: 'Abbott', slug: 'abbott', logoUrl: 'https://placehold.co/120x60/faf5ff/6b21a8?text=Abbott', createdAt: new Date().toISOString() },
];

export const mockConcerns: HealthConcern[] = [
  { id: 'con-1', name: 'Diabetes Care', slug: 'diabetes-care', iconUrl: 'Activity', description: 'Monitor & manage blood glucose levels', createdAt: new Date().toISOString() },
  { id: 'con-2', name: 'Cardiac & BP', slug: 'cardiac-bp', iconUrl: 'Heart', description: 'Hypertension & heart health wellness', createdAt: new Date().toISOString() },
  { id: 'con-3', name: 'Immunity Booster', slug: 'immunity-booster', iconUrl: 'ShieldCheck', description: 'Vitamins, Zinc & herbal supplements', createdAt: new Date().toISOString() },
  { id: 'con-4', name: 'Skin & Dermatology', slug: 'skin-dermatology', iconUrl: 'Sparkles', description: 'Skincare, acne treatments & lotions', createdAt: new Date().toISOString() },
  { id: 'con-5', name: 'Joints & Bones', slug: 'joints-bones', iconUrl: 'Bone', description: 'Calcium, Vitamin D3 & pain relief', createdAt: new Date().toISOString() },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Multivitamin Daily Health Capsules (60 Softgels)',
    slug: 'multivitamin-daily-health-capsules',
    description: 'Comprehensive daily multivitamin with Zinc, Vitamin D3, B12 & Ginseng for energy and immune support.',
    categoryId: 'cat-2',
    brandId: 'brand-5',
    mrp: 699,
    salePrice: 499,
    stockQty: 50,
    sku: 'HLTH-MVI-001',
    requiresPrescription: false,
    isActive: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Digital Blood Pressure Monitor (Automatic Upper Arm)',
    slug: 'digital-blood-pressure-monitor',
    description: 'Medical-grade automatic digital BP machine with large LCD screen and pulse arrhythmia indicator.',
    categoryId: 'cat-6',
    brandId: 'brand-5',
    mrp: 2499,
    salePrice: 1799,
    stockQty: 25,
    sku: 'DEV-BP-002',
    requiresPrescription: false,
    isActive: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Amoxycillin 500mg Antibiotic Capsules (10 Strip)',
    slug: 'amoxycillin-500mg-capsules',
    description: 'Broad-spectrum prescription antibiotic for bacterial infections. Requires valid doctor prescription.',
    categoryId: 'cat-1',
    brandId: 'brand-1',
    mrp: 145,
    salePrice: 110,
    stockQty: 100,
    sku: 'MED-AMX-500',
    requiresPrescription: true,
    isActive: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Pure Herbal Chyawanprash Immunity Booster (1 kg)',
    slug: 'pure-herbal-chyawanprash',
    description: 'Traditional Ayurvedic immunity booster enriched with Amla, Giloy, Ashwagandha & 40+ herbs.',
    categoryId: 'cat-4',
    brandId: 'brand-4',
    mrp: 399,
    salePrice: 329,
    stockQty: 40,
    sku: 'AYU-CHW-100',
    requiresPrescription: false,
    isActive: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Metformin 500mg Sustained Release Tablets (15s)',
    slug: 'metformin-500mg-sr-tablets',
    description: 'First-line medication for Type-2 Diabetes management. Strict doctor prescription required.',
    categoryId: 'cat-1',
    brandId: 'brand-2',
    mrp: 65,
    salePrice: 48,
    stockQty: 80,
    sku: 'MED-MET-500',
    requiresPrescription: true,
    isActive: true,
    thumbnailUrl: 'https://5.imimg.com/data5/SELLER/Default/2024/9/448127068/IU/CN/OA/228799824/glycomet-sr-500mg-metformin-sustained-release-tablets-1000x1000.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Hydrating Face Moisturizing Lotion with Ceramide (200ml)',
    slug: 'hydrating-face-moisturizing-lotion',
    description: 'Dermatologist recommended non-comedogenic moisturizing lotion for sensitive skin.',
    categoryId: 'cat-3',
    brandId: 'brand-3',
    mrp: 550,
    salePrice: 425,
    stockQty: 30,
    sku: 'SKN-MST-200',
    requiresPrescription: false,
    isActive: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
